package org.thesis.simulation;

public enum DeviationType {
    NONE,
    RAW_IDENTIFIER_LEAKAGE,
    PROFILE_DISALLOWED_FIELD,
    UNSUPPORTED_SCHEMA_VERSION,
    UNDECLARED_FIELD_ADDITION,
    RECEIVER_PROFILE_MISMATCH,
    INCOMPATIBLE_POLICY_METADATA,
    PROPERTY_AUTHORISATION_FAILURE,
    CROSS_SECTOR_OVER_SHARING
}
