package org.thesis.validation;

public enum RejectionCode {
    MALFORMED_JSON,
    UNDECLARED_FIELD,
    MISSING_REQUIRED_FIELD,
    UNSUPPORTED_SCHEMA_VERSION,
    DIGEST_MISMATCH,
    RAW_IDENTIFIER_LEAKAGE,
    CI_PROFILE_NOT_FOUND,
    CI_SENDER_MISMATCH,
    CI_RECEIVER_MISMATCH,
    CI_SUBJECT_MISMATCH,
    CI_INFORMATION_TYPE_DISALLOWED,
    CI_TRANSMISSION_PRINCIPLE_DISALLOWED,
    RECEIVER_PROFILE_MISMATCH,
    POLICY_PURPOSE_DISALLOWED,
    POLICY_RETENTION_EXCEEDED,
    POLICY_ONWARD_SHARING_DISALLOWED,
    PROPERTY_GRANT_NOT_FOUND,
    PROPERTY_AUTHORISATION_FAILURE
}
